### ISSUE TITLE
Do not work with Items, that have a probability instead of a numeric constant

### ISSUE THREAD

**Issue by Be-Cool-Man** [KvaNTy/MPRD#3]
In my case is the "Base Game" and the mod "DirtyMining" by Reika involved.

Base Game:
In the Centrifuge the Products "Uranium-235" and "Uranium-238" dont get listet. Neither in the "Uranium processing" tab nor in the "Kovarex enrichment process" tab.

DirtyMining:
in the Ore Washing Plant are all ores affected. None of them lists their products.

---

Installed Mods:

    5dim_autofill_0.16.0
    5dim_automatization_0.16.6
    5dim_battlefield_0.16.9
    5dim_botrecaller_0.16.3
    5dim_core_0.16.7
    5dim_decoration_0.16.4
    5dim_energy_0.16.8
    5dim_equipment_0.16.4
    5dim_fix_0.16.0
    5dim_infiniteresearch_0.16.6
    5dim_logistic_0.16.7
    5dim_mining_0.16.8
    5dim_module_0.16.4
    5dim_nuclear_0.16.6
    5dim_ores_0.16.8
    5dim_resources_0.16.10
    5dim_trade_0.16.3
    5dim_trains_0.16.7
    5dim_transport_0.16.8
    5dim_vehicle_0.16.5
    AtomicArtillery_0.1.5
    attach-notes_0.2.3
    backpacks_0.1.3
    BigDrills_0.5.1
    BigStorageTank_0.0.5
    boblibrary_0.16.6
    creative-mode-fix_0.0.32
    DirtyMining_1.0.64
    ElectricTrain_0.16.5
    factory-floor_0.1.2
    Flow Control_3.0.3
    FNEI_0.1.8
    Helicopters_0.2.16
    Infinizoom_0.1.2
    LightedPolesPlus_1.1.3
    LoaderRedux_1.2.7
    LogisticTrainNetwork_1.7.10
    mod-list.json
    mod-settings.dat
    multi-product-recipe-details_0.16.3
    MushroomCloud_1.0.3
    NapalmArtillery_0.16.3
    Noxys_Trees_0.0.13
    OmegaDrill_0.1.6
    radarplus for rso_0.0.5
    ReallyPressureTanks_1.0.0
    research-queue_1.6.4
    Robocharger_1.1.0
    rso-mod_3.7.7
    ScanningRadar_0.2.9
    Squeak Through_1.2.2
    StorageTank2_0.3.0
    Subterranean_0.5.1
    UltimateBelts_0.16.4
    upgrade-planner_1.5.3
    Vehicle Wagon_1.2.5
    vtk-ta-big-bertha-artillery-sounds_1.1.1
    Warehousing_0.1.3
    Wind_Turbine V16_4.0.5

**Comment by KvaNTy** [comment]
I somehow overlooked it. Probably because MadClown's mods make uranium enrichment process different.

Thanks for noticing that.
